version: '3'

services:
  release-server:
    image: traeger/release-server:latest
    working_dir: /app
    ports: 
      - "5001:5001"
    volumes: 
      - ./appsettings.json:/app/appsettings.json
      - ./artifacts:/app/artifacts
      - ./backups:/app/backups
