version: '3'

services:
  release-server:
    image: ghcr.io/traeger-gmbh/release-server:latest
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - "CREDENTIALS_USERNAME=TestUser"
      - "CREDENTIALS_PASSWORD=SomePassword"
    volumes: 
      - backups:/app/backups
      - artifacts:/app/artifacts
volumes:
  artifacts:
  backups:
