name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ./sources/ReleaseServer/
    - name: Build
      run: dotnet build ./sources/ReleaseServer/ --configuration Release --no-restore
    - name: Test
      run: dotnet test ./sources/ReleaseServer/ --no-restore --verbosity normal
